config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/auth/facebook/callback' => 'sessions#create'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get 'users', to: 'users#index', as: 'users'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # get 'movies/newest', to: "movies#newest", as: 'newest'

  post 'movies/:id/watched', to: 'movies#watched', as: 'watched'

  resources :users, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]

	resources :movies 
   
   resources :movies, only: [:show] do
    resources :comments, only: [:index, :new, :create, :destroy]
  end
    
  resources :directory, only: [:show]
  resources :genres

  # post 'movies/:id/favorite', to: 'movies#favorite', as: 'favorite'
  # get 'genre/newest', to: "genres#newest", as: 'newest'
  
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  

  def index
		@movies = Movie.all
		render json: @movies
  end

  def new
    @movie = Movie.new
    @movie.build_genre
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    if @movie.save
      @movie.update(user_id: current_user.id)
      
      redirect_to genres_path, flash: {success: "'#{@movie.title}' was added!"}
    else
      flash.now[:error] = "Please enter all fields"
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @comments = @movie.comments
    @comment = Comment.new

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @movie}
    end
    
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to movie_path(@movie), flash: {success: "#{@movie.title} was updated"}
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    flash[:success] = "#{@movie.title} has been deleted."
    redirect_to directory_path(current_user.id)
  end

  def watched
    @movie = Movie.find(params[:id])
    if @movie.user_id = current_user.id
      @movie.watched = !@movie.watched 
      @movie.save
      redirect_to directory_path(current_user.id), flash: {success: "Movie has been watched!"}
    else
      flash[:error] = "Movie was not added to watched movies."
    end
  end

  private


    def movie_params
      params.require(:movie).permit(:title, :year, :description, :director, :genre_id, :genres_attributes => [:id, :name, :_destroy])
    end


end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<h3>The form below is to add a movie to an existing genre at the directory.<br>
      If you'd like to add a new movie AND genre,
    <%=link_to 'click here', new_genre_path %>.</h3>


<%= form_for @movie, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>
  </div><br>

 <div class="field">
    <%= f.label :year, "Year" %>
    <%= f.text_field :year %>
  </div>
  <br>
  <div class="field">
      <%= f.label :director, "Director:"%><br>
      <%= f.text_field :director%><br>
      <br>
    </div>

  <div class="field">
    <%= f.label :description, "Write a short Movie Summary:" %><br>
    <%= f.text_area :description, size: "24x6" %>
  </div>

  <h3> Choose a genre: </h3>
       <%= f.collection_radio_buttons :genre_id, Genre.all, :id, :name %>
      <br>

   <%= f.submit class: 'btn btn-success' %>

   <% end %>


   

app/views/movies/edit.html.erb
<h1>Edit <%= @movie.title  %> </h1>

<%= render 'form'  %>

app/views/movies/new.html.erb
<h1>Add a New Movie</h1>

<%= render 'form'  %>

app/views/movies/show.html.erb
<h2> <%= @movie.title %></h2>
<h3>Director: <%= @movie.director %></h3>
<h4><%= @movie.year %></h4>
<p><strong>Description:</strong> <%= @movie.description %></p>


<p><strong>Availability:</strong></p>
   <% if @movie.available? %>
       <p>This movie is available.</p>
          <p><%= button_to 'Add to Watched Movies', watched_path %></p>
          <% else %>
             <p><strong>Sorry, this movie isn't available. </strong></p>
          <% end %>

          

 <h2>Comments</h2>
 <% if @movie.comments != [] %>

  <% @movie.newest_comment.each do |comment| %>
       <strong>Comment by <%= comment.user.username%></strong><br>
       <%= comment.body %>
       <br>
       <br>
       <div class="new">
        <!-- <p> Comment by: <%= comment.user.username %> </p> -->
       </div>
         <% if comment.user_id == current_user.id %>
         <%= link_to 'Delete Comment', movie_comment_path(@movie, comment), method: :delete %><br>
         <% end %>
      <% end %>
     <br>

  


     <%= link_to "Click here to load all of #{@movie.title}'s comments", movie_comments_path(@movie), class: "all_comments" %>
     <br>
     <div class="comments">

     </div>
     <% else %>
     <p> There are no comments yet!</p>
     <% end %>

   <h2>Add a comment:</h2>

 <%= form_for([@movie, @comment]) do |f| %>
   <%= f.text_area :body %>
   <p><%= f.submit %></p>
<% end %>