config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/auth/facebook/callback' => 'sessions#create'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get 'users', to: 'users#index', as: 'users'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # get 'movies/newest', to: "movies#newest", as: 'newest'

  post 'movies/:id/watched', to: 'movies#watched', as: 'watched'

  resources :users, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]

	resources :movies 
   
   resources :movies, only: [:show] do
    resources :comments, only: [:index, :new, :create, :destroy]
  end
    
  resources :directory, only: [:show]
  resources :genres

  # post 'movies/:id/favorite', to: 'movies#favorite', as: 'favorite'
  # get 'genre/newest', to: "genres#newest", as: 'newest'
  
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-fixed-top" id="mainNav">
    <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/"> FilmFan </a>
    </div>
  
        <ul class="nav navbar-nav ml-auto">

        <% if !!current_user %>
            <li class="nav-item">
              
              <%= link_to "Directory", directory_path(current_user) %>
              <%= link_to "Genres", genres_path %>
              <%= link_to logout_path, method: :delete, class: 'nav-link' do %>
                  <span class="log-out"></span> Sign Out
              <% end %>
            </li>
        <% else %>
           <li class="nav-item"><%= link_to "Log in", login_path %></li>
          <li class="nav-item"> <%= link_to "Sign Up", signup_path %> </li>
        <% end %>
        </ul>
    
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilmFanRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= render 'shared/flash_messages' %>

    <div id="main-container" class="container">
    
      <%= yield :form_errors %>

      <%= yield %>
    </div>


  </body>

  
    
</html>